# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap

exclude:
  - "/vendor/"

# Site settings
title: "Santa Monica College Students <br> for Bernie Sanders"
title-footer: "Santa Monica College Students for Bernie Sanders"
subtitle: "SMC Chapter of College Students for Bernie Sanders"
email: SmcforBernie@gmail.com
name: Bernie Bernie Bernie
description: >
  SMC Chapter of College Students for Bernie Sanders
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://avelinakim.github.io" # the base hostname & protocol for your site
cover: "/assets/imgs/bernie-stage.jpg"
logo: "/assets/imgs/Sanders-logo-white.png"
permalink: "/:categories/:title/"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai_sublime"

# Disqus comments
disqus_shortname: bencentra

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:

  - name: Facebook
    icon: facebook
    username: SMC for Bernie fb group
    url: https://www.facebook.com/groups/556637134498576/
    desc: Join our Facebook group
    share: true

  - name: YouTube
    icon: youtube
    username:
    url:
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username:
    url:
    desc: Follow me on Instagram
    share: false

  - name: Pinterest
    icon: pinterest
    username:
    url:
    desc: Follow me on Pinterest
    share: true


  - name: Tumblr
    icon: tumblr
    username:
    url:
    desc: Follow me on Tumblr
    share: false


# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/RichardLitt/wordhoardpress.com"
    os_rcs_type: "git"
    os_src: "git@github.com:RichardLitt/wordhoardpress.com.git"

# Officers
officers:
  - name: Alfredo Gama
    position: President
    description: "I am a second year student at Santa Monica College. My interests are very diverse. 
    They  include Political Economy and Biochemistry. I am organizing for Bernie because I understand
     that this is not just a moment, but a movement. It's a movement composed of the most energetic 
     young people in the country. I understand that we, as millennials, must partake in the change we 
     want to see. Bernie Sanders has introduced many young people into the political process. I 
     organized this group to take Bernie's message around California, but also beyond the campaign 
     season. When Bernie becomes our 45th President of the United States, the movement will continue. 
     The fight to end income inequality, to combat climate change, to end racial disparity, the 
     persecution of undocumented immigrants and many more battles will continue. Because when we fight,
     win!"
    img: "/assets/imgs/alfredo.jpg"

  - name: Avelina Kim
    position: Vice President
    description: "I am in my second year of studying Computer Science at SMC. My hobbies include 
    playing League of Legends and programming. I support Bernie Sanders because he is the 
    only candidate who is not owned by corporations and who actually represents the American people. 
    He fights for women, the LGBTQ community, minorities, the poor, and the environment, not just the 
    top 1%. He is also the best candidate for the economy because he will redistribute wealth in 
    America, increasing the velocity of money. But Bernie cannot do it alone, he needs the American
    people to stand together and take action." 
    img: "/assets/imgs/avelina.jpg"

  - name: Daira Bustos
    position: Treasurer
    description: 
    img: "/assets/imgs/daira.jpg"

  - name: Leo Martinez
    position: Voter Registration Coordinator
    description: "I am a History and Anthropology major. I have been at SMC for two years. I enjoy 
    watching movies, playing video games and reading JSTOR articles. I support Bernie because he is a 
    continuation of Theordore Roosevelt, Franklin Roosevelt and Lyndon B. Johnson, progressive icons who
    defied the odds and pushed an agenda for the American people and not corporations. I support Bernie 
    because he is the real deal."
    img: "/assets/imgs/leo.jpg"

  - name: Stephanie Mendez
    position: Outreach Director
    description: "I am a political science major and have been at SMC for one year. I will soon be the future
    Director of Instructional Support. I am on the SMC Speech and Debate team, and have won against the 
    Japanese National debate team as well as win gold at PSCFA Champs. My hobbies include debate as well as 
    reading. I believe in Bernie Sanders because I truly believe he is a man of the people. During one of his
    rallies, black lives matter protesters interjected and spoke, AND HE LISTENED. Not only do I believe 
    he is a great candidate, but the political revolution he's encouraged has lead to great outcomes in 
    finding solutions and being politically active."
    img: "/assets/imgs/stephanie.jpg"
